pages:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  image: busybox
  script:
  - mkdir -p public
  - mv .* * public/. || true
  artifacts:
    paths:
    - public
  only:
  - master
